version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'  # Next.js default port
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - '5000:5000'  # Example backend port
    environment:
      NODE_ENV: development
